---
title: "report"
output: pdf_document
---

#plot_age_proteins #plot_age_regression
These plots visualises how the top 10 variable proteins change with Age.
Protein CHIT1 increased with age: 
Older adults have more activated macrophages (white blood cells that act as ‘first responders’ to infections/injuries) and
release CHIT1 as part of the inflammatory response.
Macrophages become overactive with age and produce excess inflammatory cytokines which contributes to chronic low-grade inflammation.
Protein NEFH increased with age:
NEFH is a neurofilament protein released during axonal stress or turnover. 
With age, neurons have slower repair mechanisms and degeneration. 

#plot_age_sex
This plot uses colour to visualise how sex affects the change in the top 10 variable proteins with Age. 
All of these proteins showed relatively equal colouring of male (blue) and female (red) participants. This means the age-related patterns observed earlier are not strongly sex-dependent.

#plot_sex_box
This box plot displayed relatively similar protein expression distribution between Male and Female, supporting plot_age_sex .

#plot_sex_classifier
Total correct predictions: 38 (Female -> Female) + 24 (Male -> Male) = 62
Total samples: 150
Accuracy around 41%, which is below random guessing for a balanced dataset (50%).
This shows that the classifier did not demonstrate a strong ability to distinguish between males and females.

#plot_corr_heatmap
This correlation heatmap showed mild correlation between certain proteins as well as between Age and proteins. 

Future directions: 
- Study influence of more participant features in analysis 
Eg. health status, lifestyle factors. 
- Longitudinal analysis
Integrate temporal data, studying participants' protein expression over time would strengthen interpretation of age-related effects.
- Combine with multi-omics data
eg. genomics can help us identify patterns not visible in proteins alone.


Running:
make
regenerates the entire project 

This report was generated with:
rmarkdown::render("report.Rmd", output_format = "pdf_document")
inside a Docker container defined in the provided Dockerfile.
